global:
  resolve_timeout: 5m

# Route configuration
route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true

    # Warning alerts - grouped notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      group_interval: 5m

# Receiver configurations
receivers:
  - name: 'default-receiver'
    # Placeholder - configure your notification channels

  - name: 'critical-alerts'
    # Example: Slack webhook
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#central-mcp-alerts'
    #     title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'warning-alerts'
    # Example: Email notifications
    # email_configs:
    #   - to: 'team@example.com'
    #     from: 'alertmanager@central-mcp.com'
    #     smarthost: 'smtp.gmail.com:587'

# Inhibition rules (prevent alert spam)
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
